version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/app/
    overwrite: true
file_exists_behavior: OVERWRITE
hooks:
  AfterInstall:
    - location: scripts/change_permissions
      timeout: 300
      runas: root
